apiVersion: v1
kind: Service
metadata:
  name: workshop-api
  labels:
    app.kubernetes.io/name: workshop-api
spec:
  type: NodePort
  ports:
    - port: 7001
      targetPort: 7001
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: workshop-api
