apiVersion: apps/v1
kind: Deployment
metadata:
  name: workshop-frontend
  labels:
    app.kubernetes.io/name: workshop-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: workshop-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: workshop-frontend
    spec:
      containers:
        - name: workshop-frontend
          image: joelluijmes/workshop-frontend
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
