apiVersion: v1
kind: Service
metadata:
  name: workshop-frontend
  labels:
    app.kubernetes.io/name: workshop-frontend
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: workshop-frontend
